##############################
#      KarmaPoints v 1.0     #
#                            #
#  Разработчик: krovyaka     #
#  vk.com/krovyaka           #
##############################

# Задержка между комадами с кулдауном (в минутах).
delay-in-minutes: 2

# Сообщение во время кулдауна. %d означает то место, куда будет подставлено время задержки в минутах.
delay-message: §cПодождите ещё %d минут.

# Сообщение при отсутствии прав на команду.
no-permission-message: §cУ вас нет прав.

# Сообщение при отсутствии игрока на сервере, когда его ник указан как аргумент в команде.
no-player-message: §cЭтот игрок не находится в игре или не существует.

# Ответ на команду /point time. %d означает то место, куда будет подставлено время задержки в минутах.
time-message: §eДо следующей команды ещё %d минут.

# Ответ на команду /point time, когда задержки нет.
no-time-message: §eВы можете использовать команды.

# Заголовок топа во время использования /point top.
top-message: '§6Топ игроков:'

# Один из элементов в этом топе. %s означает Имя игрока, а %d означает его количество очков.
top-element-message: '§6%s: §e%d'

# Ответ на сообщение /point ahelp.
admin-help: >
§aТут будет текст, который появляется
При написании команды /point ahelp.

# Сообщение об использовании команды /point good.
good-message: §eВы добавили игроку одно очко кармы.

# Сообщение об использовании команды /point bad.
bad-message: §eВы лишили игрока одного очка кармы.

# Сообщение, которое вернётся админу, написавшему /point display. %d означает число поинтов, которое будет подставлено.
display-message: §6У данного игрока %d очков кармы.

# Сообщение при использовании команды /point rob.
rob-message: §eВы лишили игрока части его очков кармы.

# Сообщение при использовании команды /point add.
add-message: §eВы дали игроку очки кармы.

# Сообщение при использовании команды /point set.
set-message: §eВы установили игроку очки его кармы.

# Сообщение при использовании команды /point gift.
gift-message: §eВы подарили данному игроку часть своих очков кармы.

# Сообщение при некорректном использовании /point gift.
gift-message: §cВведено неверное число, либо у Вас нет столько очков кармы.

# Сообщение о том, что данный функционал ещё не реализован и будет в следующих обновлениях
no-realization-message: §6Данная возможность ещё не реализована!