name: KarmaPoints
main: com.KarmaPoints
author: krovyaka
version: 0.2
description: Current plugin makes you get a karma points for a while you just in the game. So, whatever, you can gift karma points to the other players.

commands:
 point:
   description: Main command of the KarmaPoints plugin.
   usage: /point help - to get the full plugin information.
   permission: karmapoints.point
   aliases: [p, karmapoints]